### ISSUE TITLE
Oracle connection - Error Message : ORA-00904: invalid identifier

### ISSUE THREAD

**Issue by IDLE-Max** [Neconix/Yii2-Oci8#1]
Hi,

I have an issue with an oracle connection.

> The SQL being executed was: SELECT COUNT(_) FROM "VT_COUREUR" "cou" LEFT JOIN "VT_PAYS" "pay" ON pay.CODE_TDF = cou.CODE_TDF
> ↵
> Caused by: Yajra\Pdo\Oci8\Exceptions\Oci8Exception
> Error Code : 904
> Error Message : ORA-00904: "COU"."CODE_TDF": invalid identifier
> Position : 84
> Statement : SELECT COUNT(_) FROM "VT_COUREUR" "cou" LEFT JOIN "VT_PAYS" "pay" ON pay.CODE_TDF = cou.CODE_TDF
> Bindings : []

And here is my code :

`$query = Coureur::find()->from('VT_COUREUR cou')
                                ->join("left join",'VT_PAYS pay','pay.CODE_TDF = cou.CODE_TDF');`

**Comment by Neconix** [comment]
@IDLE-Max, try to add quotes in the join condition string:

`$query = Coureur::find()`
`->from('VT_COUREUR cou')`
`->join("left join",'VT_PAYS pay','"pay"."CODE_TDF" = "cou"."CODE_TDF"');`

**Comment by IDLE-Max** [comment]
Unfortunatly, it doesn't work. I have the same error.

> Error Code : 904
> Error Message : ORA-00904: "cou"."code_tdf": invalid identifier
> Position : 88
> Statement : SELECT COUNT(_) FROM "VT_COUREUR" "cou" LEFT JOIN "VT_PAYS" "pay" ON "pay"."code_tdf" = "cou"."code_tdf"
> Bindings : []
> The SQL being executed was: SELECT COUNT(_) FROM "VT_COUREUR" "cou" LEFT JOIN "VT_PAYS" "pay" ON "pay"."code_tdf" = "cou"."code_tdf"

The following code is my db connexion.

```
return [
'class' => 'neconix\yii2oci8\Oci8Connection',
    'dsn' => 'oci:dbname=//192.168.56.101:1521/XE;charset=AL32UTF8;',
    'username' => 'system',
    'password' => 'o',
    'attributes' => [ PDO::ATTR_PERSISTENT => true ],
    'enableSchemaCache' => true, //Oracle dictionaries is too slow :(, enable caching
    'schemaCacheDuration' => 60 * 60, //1 hour
    'on afterOpen' => function($event) {
        $q = <<<SQL
begin
  execute immediate 'alter session set NLS_COMP=LINGUISTIC';
  execute immediate 'alter session set NLS_SORT=BINARY_CI';
  execute immediate 'alter session set NLS_TERRITORY=AMERICA';
  execute immediate 'alter session set NLS_DATE_FORMAT=''DD/MM/YYYY''';
end;
SQL;
        $event->sender->createCommand($q)->execute();
    }
];
```

If I use table names like `VT_COUREUR.CODE_TDF = VT_PAYS.CODE_TDF` instead of aliases, it works pretty well. But I need aliases in another search model (I have two foreign keys on the same table).

**Comment by Neconix** [comment]
Which version of Yii2 is used? Generated query part with 'count()' looks strange here.

**Comment by Neconix** [comment]
Also, I have ORA-00904 error when trying to execute query with a fields in lower case:
`"pay"."code_tdf" = "cou"."code_tdf"` - error
`"pay"."CODE_TDF" = "cou"."CODE_TDF"` - ok

**Comment by IDLE-Max** [comment]
Yii 2.0.8. I solved this issue by writting in uppercase aliases and columns.

```
$query = Coureur::find()->from("VT_COUREUR COU");
$query->join("LEFT JOIN",'VT_PAYS PAY','PAY.CODE_TDF = COU.CODE_TDF');
```

Thanks for your help @Neconix .
