### ISSUE TITLE
Connection does not support reading schema information for 'oci8' DBMS.

### ISSUE THREAD

**Issue by fdo36** [Neconix/Yii2-Oci8#2]
I have configured oci8 in my apache. In fact, when I use the yii\db\Connection, it works fine:

```
return [
	'class' => 'yii\db\Connection',
	'dsn' => 'oci:dbname=//127.0.0.1:1521/xe',
	'username' => 'test',
	'password' => '1234test',
	'charset' => 'AL32UTF8',
]

```

But I want to try your widget and throws me this error:

> Exception 'yii\base\NotSupportedException' with message 'Connection does not support reading schema information for 'oci8' DBMS.'
> 
> in C:\xampp\htdocs\cms\vendor\yiisoft\yii2\db\Connection.php:827
> 
> Stack trace:
> #0 C:\xampp\htdocs\cms\vendor\neconix\yii2-oci8\src\Oci8Connection.php(85): yii\db\Connection->getSchema()
> #1 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\base\Component.php(139): neconix\yii2oci8\Oci8Connection->getSchema()
> #2 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\console\controllers\MigrateController.php(210): yii\base\Component->__get('schema')
> #3 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(875): yii\console\controllers\MigrateController->getMigrationHistory(NULL)
> #4 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->getNewMigrations()
> #5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
> #6 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
> #7 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
> #8 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\console\Controller.php(148): yii\base\Controller->runAction('', Array)
> #9 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\base\Module.php(528): yii\console\Controller->runAction('', Array)
> #10 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate', Array)
> #11 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate', Array)
> #12 C:\xampp\htdocs\cms\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))

How can I fix it?

**Comment by filsav** [comment]
You should use:

`'class' => 'neconix\yii2oci8\Oci8Connection',`

**Comment by fdo36** [comment]
as I said. When I use that configuration (when I try to use that class) appears the error I quoted... And when I use the default configuration there is no error.

**Comment by Neconix** [comment]
Hi! Is the problem still relevant? If yes, then please provide more information about your configuration files.
